### ISSUE TITLE
Attribute error with predicting new tags [BUG]

### ISSUE THREAD

**Issue by arinzea** [GRAAL-Research/deepparse#101]
I am trying to retrain with new prediction tags from the example here [https://deepparse.org/examples/retrain_with_new_prediction_tags.html](url)

`address_parser.test(test_container, batch_size=256)` returns test accuracy of 96%
`Running test
Test steps: 4 0.37s test_loss: 0.703016 test_accuracy: 96.733354                               
{'time': 0.3694855499998084,
 'test_loss': 0.7030158100128174,
 'test_accuracy': 96.73335400390626}`

However I want to use the new retrained model with the tags to predict on the test data but I am getting an error
`AttributeError: 'FormattedParsedAddress' object has no attribute 'ATag'`

![image](https://user-images.githubusercontent.com/6643795/136812792-790be19c-2a0a-4b00-a92b-4f4b54f8a771.png)

**Expected behavior**
I am expecting a new vectorized address that can be converted into a dataframe.

**Comment by davebulaval** [comment]
Can you share more code? I have two hypotheses about the problem.
