### ISSUE TITLE
No 'EOS' attribute when parsing uncorrectly spaced address

### ISSUE THREAD

**Issue by riccardoruspoli** [GRAAL-Research/deepparse#106]
**Describe the bug**
When an address containing a comma with spaces before __and__ after is parsed, an AttributeError with the following description is thrown: `AttributeError: 'FormattedParsedAddress' object has no attribute 'EOS'`.

**To Reproduce**
Executing these 5 lines, with the example address from README.md given as input, will result on the AttributeError being thrown only at the fifth line.
<pre>
address_parser('350 rue des Lilas Ouest Québec Québec G1L 1B6')<br>address_parser('350 rue des Lilas,Ouest Québec Québec G1L 1B6')<br>address_parser('350 rue des Lilas, Ouest Québec Québec G1L 1B6')<br>address_parser('350 rue des Lilas ,Ouest Québec Québec G1L 1B6')<br>address_parser('350 rue des Lilas , Ouest Québec Québec G1L 1B6')
</pre>

**Tech stack**
 - Windows 10
 - Python 3.9.5
 - Deepparse 0.5.1

**Additional context**
The temporary fix is to remove a space or the comma to match one of the other working cases.

**Comment by davebulaval** [comment]
Fixed in #109 and version release 0.6.1
