### ISSUE TITLE
Error at importing AddressParser[BUG]

### ISSUE THREAD

**Issue by munozariasjm** [GRAAL-Research/deepparse#121]
**Describe the bug**
When triying to import AddressParser there seems to be a problem with gensim.

**To Reproduce**
On a brand new colab. Just do:
```python
!pip install deepparse
from deepparse.parser import AddressParser
```
Then, the error is:
```python
ImportError: cannot import name 'load_facebook_vectors' from 'gensim.models.fasttext' (/usr/local/lib/python3.7/dist-packages/gensim/models/fasttext.py)
```
The bug gets easilly solved doing:
```
!pip install -U gensim
```
Thus, I think it would be very good to add 
```
pip install gensim==4.1.2
```
to the requirements.
Regards, and thanks for the effort! :1st_place_medal: 

**Setup:**
 - python 3.7

**Comment by MAYAS3** [comment]
Hello @munozariasjm,

Gensim is already part of the requirements and installs properly upon installing deepparse. There was a missing dependency for pandas which I have just fixed but everything you need to run the package is included in the setup.

Are you running the latest version of deepparse?
If not could you upgrade and try again?

Il the problem persists, could you please provide some more information about your OS and the environment you're running deepparse in?

**Comment by munozariasjm** [comment]
Hi!, thanks for the fast answer! :rocket: 
Yes, I was working on the develop at
```https://github.com/GRAAL-Research/deepparse.git@dev```.
But now it works like a charm.

Best regards!

**Comment by hummingbird1989** [comment]
@MAYAS3 I'm facing the same issue when running in Colab. Is there a specific version of deepparse I should be using?
I'm using `deepparse==0.7.4` and `gensim===4.2.0`

**Comment by davebulaval** [comment]
I will force the setup to use a recent version of `gensim`. Tks for the follow up.
