### ISSUE TITLE
[BUG] Pip install fails : still try to install fasttext

### ISSUE THREAD

**Issue by HayatoSempai** [GRAAL-Research/deepparse#196]
Hello,

I am trying to install deepparse last version (0.9.7) but it still tries to install fasttext. The install fails because of this MR context : https://github.com/GRAAL-Research/deepparse/pull/195.
But when I launch `pip install deepparse` it fails because it installs fasttext.

I have seen that in https://github.com/GRAAL-Research/deepparse/blob/main/setup.py we can see that 
`        install_requires=[
            "numpy",
            "torch",
            "bpemb",
            "gensim>=4.0.0",
            "requests",
            "fasttext",
            "pymagnitude-light",
            "poutyne",
            "pandas",
            "urllib3",
        ],`
 Is it possible to replace fasttext with fasttext-wheel ?
 
 Thanks
 
**Desktop (please complete the following information):**
 - OS: Mac
 - Version M1 Pro

**Comment by davebulaval** [comment]
You are right, I forgot to update the `setup.py` `install_requirements`.

Fixed in 0.9.8.
