### ISSUE TITLE
Script to bundle it into an API

### ISSUE THREAD

**Issue by Gayathri2993** [GRAAL-Research/deepparse#199]
Has anyone got a script to bundle fasttext model as an API to run like a live 24/7 service?

**Comment by davebulaval** [comment]
@Gayathri2993 ?

**Comment by Gayathri2993** [comment]
Apologies for the delayed reply. I am looking for something like FastAPI wrapup code for easy deploy

**Comment by davebulaval** [comment]
Alright, I will take a look at offering such a codebase.

**Comment by Gayathri2993** [comment]
@davebulaval I wanted to check in regarding the feature request. I would appreciate it if you could let me know if you had the opportunity to review it.

**Comment by Gayathri2993** [comment]
@davebulaval  Thank you for taking up this up. I will definitely test it

**Comment by davebulaval** [comment]
We have just merged in dev the PR #206 that proposes a FastAPI along with a docker file to bundle Deepparse as an API. 

We would greatly take your comments on the doc and the functionalities.

**Comment by davebulaval** [comment]
Release in 0.9.9.
