### ISSUE TITLE
training a model for non Latin language

### ISSUE THREAD

**Issue by maherr13** [GRAAL-Research/deepparse#216]
Hello

I'm trying to use your package for training address parser for arabic (different letters from proposed languages), do you offer this feature ? if so would you guide me how to achieve this. 

Thanks

**Comment by MAYAS3** [comment]
Hello @maherr13,

Deepparse's models are multilingual, so they should support the arabic language as long as the dataset is defined properly. 

You can take a look at our retraining tutorial (https://deepparse.org/examples/fine_tuning.html) and our training guide (https://deepparse.org/training_guide.html) for more information on how to train the models on your data.

Let me know if you have any questions!

**Comment by maherr13** [comment]
![image](https://github.com/GRAAL-Research/deepparse/assets/83926003/5abde517-69fb-4234-b0ef-39abc6f7a9d8)
I read this part in the paper, do you think it will work with Arabic letters?

**Comment by davebulaval** [comment]
@maherr13 it works in Japanese, Chinese and other non-Latin languages. I am pretty sure it will work.

**Comment by MAYAS3** [comment]
@maherr13 I'm closing this issue. Feel free to experiment with our models and let me know if you encounter any issues.
