### ISSUE TITLE
Clarification on performance results

### ISSUE THREAD

**Issue by vanga** [GRAAL-Research/deepparse#219]
Hi,

I am looking at the performance metrics [here](https://deepparse.org/parser.html#memory-usage-and-time-performance
). I want to know which CPU and the number of cores used.
I can see that the type of GPU used is mentioned in the [paper](https://arxiv.org/pdf/2311.11846.pdf), but I couldn't find any such info about CPU. Could you please share that info?

Thanks.

**Comment by vanga** [comment]
Since the published metrics are mean execution times for an address, information of number of cores is probably irrelevant? 
However the actual type of CPU device will matter I guess?

**Comment by MAYAS3** [comment]
Hello @vanga,

I believe the benchmarks were done on an **AMD Ryzen 7 2700X**. Do you confirm @davebulaval ?

**Comment by davebulaval** [comment]
It was done on a single-thread processing, and yes, on a Ryzen 7 2700X from AMD.
