### ISSUE TITLE
Won't install using Poetry and recent pandas.

### ISSUE THREAD

**Issue by drobert-bfm** [GRAAL-Research/deepparse#220]
There's a version conflict due to the possibly over-restrictive dependency declared by deepparse on Pandas 2.0.3. Projects which require a recent version of Pandas for other reasons can't install deepparse without triggering this version conflict. Pip will tolerate this (it shouldn't), but poetry refuses to install deepparse as a result.

To reproduce:

- create a Poetry-managed project
- poetry add pandas
- poetry add deepparse

Expected Behaviour:

Both current versions of pandas and deepparse install correctly.

**Comment by davebulaval** [comment]
I have fixed it in the dev remote. You can go ahead and install the dev version until I release it.

Gensim also has a dependency problem with SciPy, so I am waiting for them to fix it before releasing a new version.

**Comment by davebulaval** [comment]
Update: Gensim does not yet support wheels for Python 3.12. 

It should be resolved soon.

https://github.com/piskvorky/gensim/issues/3510

**Comment by davebulaval** [comment]
Update: A new release is expected in the next two to three weeks ([ref](https://github.com/piskvorky/gensim/issues/3510#issuecomment-2147102376)).

**Comment by davebulaval** [comment]
It will be fixed in release 0.9.10; I have fixed the SciPy version until Gensim does a release.
