### ISSUE TITLE
[BUG] Test and retrain function doesn't update notebook output inplace

### ISSUE THREAD

**Issue by jarkkojarvinen** [GRAAL-Research/deepparse#222]
**Describe the bug**
Python Notebook terminal output starts to scroll horizontally and doesn't update existing output text. This started last week.

**To Reproduce**
```
address_parser.test(test_container, batch_size=256, num_workers=2)
```
And same applies to retrain function. It works similarily.

**Expected behavior**
Notebook output text should replace previous output inplace, not insert after previous horizontally. It is quite annoying to scroll to most right to see current progress.

**Screenshots**
<img width="1568" alt="image" src="https://github.com/GRAAL-Research/deepparse/assets/2040074/b6dde43c-4b07-4e1e-89e8-9a6d2e9801bd">

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 or Windows 11 Pro (both tested)
 - Visual Studio Code: 1.89.1

requirements.txt installed to my venv:
```
# common
Cython==3.0.10
joblib==1.4.2
numpy==1.26.2
pandas==2.0.3
python-dateutil==2.8.2
pytz==2024.1
scikit-learn==1.3.2
scipy==1.11.4
six==1.16.0
sparse-dot-topn==1.1.1
threadpoolctl==3.5.0
deepparse==0.9.9
gensim==4.3.2
fasttext-wheel==0.9.2
setuptools==68.2.2
tqdm==4.66.4
ipython==8.24.0
matplotlib==3.8.4
Faker==25.0.1
openpyxl==3.1.2

# notebooks specific requirements
ipykernel==6.29.4
nbconvert==7.16.4
nbformat==5.10.4
```

**Additional context**
NOTE: This might be related to some other Python package since this has been worked correctly earlier. This started last week. I tried to check bug reports of deepparse or mine direct deps but didnt find any relevant info. Hopefully some one had same issue and probably solved this already. And from VS Code I didn't saw any settings which helps.

**Comment by jarkkojarvinen** [comment]
Seems this is actually somekind of VS Code Notebook visualization issue since in terminal it is working. In terminal progress is updated in-place.
<img width="578" alt="image" src="https://github.com/GRAAL-Research/deepparse/assets/2040074/3ef6b0ec-2d6a-4cbe-9eca-a79fd52ab752">

**Comment by davebulaval** [comment]
I know that Python in Jupyter is not well supported for print and updates like that.
