### ISSUE TITLE
Is it possible to know the country from an address without a country?

### ISSUE THREAD

**Issue by Chris8080** [GRAAL-Research/deepparse#223]
Hello,

as an example, I'm using this code:

```
from deepparse.parser import AddressParser

address_parser = AddressParser(model_type="bpemb", device=0)
parsed_address = address_parser("Benedikt-Schmittm.-Str. 1 40479 Düsseldorf") 

print(parsed_address)
print(parsed_address.PostalCode)
print(parsed_address.Province)
```

which works nicely - the parts of the address are being recognized - IF they are there.
I'm missing the country in this example. Is it somehow possible to 'assume' or infer the country with deepparse?

**Comment by MAYAS3** [comment]
Hello @Chris8080,

Deepprase doesn't presently recognize the country out-of-the-box unfortunately. But it is something we plan on adding in the future.

In the mean time, if you have address data for you can retrain our models and add a country tag so the models can recognize the country. The docs contain a [tutorial](https://deepparse.org/examples/retrain_with_new_prediction_tags.html) on retraining with custom tags.
