### ISSUE TITLE
[BUG]  metadata-generation-failed

### ISSUE THREAD

**Issue by gen-li** [GRAAL-Research/deepparse#235]
**Describe the bug**
Collecting deepparse[app]
  Using cached deepparse-0.9.12-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: numpy<2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from deepparse[app]) (1.26.4)
Requirement already satisfied: torch in /opt/anaconda3/lib/python3.12/site-packages (from deepparse[app]) (2.4.1)
Collecting bpemb (from deepparse[app])
  Using cached bpemb-0.3.5-py3-none-any.whl.metadata (19 kB)
Collecting scipy<=1.10.1 (from deepparse[app])
  Using cached scipy-1.9.3.tar.gz (42.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      + meson setup /private/var/folders/0v/nkjttv413cgb2b1z262v54rm0000gn/T/pip-install-pm0emj9q/scipy_95d22f3313394ae88360cc627ecfbef3 /private/var/folders/0v/nkjttv413cgb2b1z262v54rm0000gn/T/pip-install-pm0emj9q/scipy_95d22f3313394ae88360cc627ecfbef3/.mesonpy-9osi9ko5 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/private/var/folders/0v/nkjttv413cgb2b1z262v54rm0000gn/T/pip-install-pm0emj9q/scipy_95d22f3313394ae88360cc627ecfbef3/.mesonpy-9osi9ko5/meson-python-native-file.ini
      The Meson build system
      Version: 1.5.1
      Source dir: /private/var/folders/0v/nkjttv413cgb2b1z262v54rm0000gn/T/pip-install-pm0emj9q/scipy_95d22f3313394ae88360cc627ecfbef3
      Build dir: /private/var/folders/0v/nkjttv413cgb2b1z262v54rm0000gn/T/pip-install-pm0emj9q/scipy_95d22f3313394ae88360cc627ecfbef3/.mesonpy-9osi9ko5
      Build type: native build
      Project name: SciPy
      Project version: 1.9.3
      C compiler for the host machine: cc (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.3.9.4)")
      C linker for the host machine: cc ld64 1053.12
      C++ compiler for the host machine: c++ (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.3.9.4)")
      C++ linker for the host machine: c++ ld64 1053.12
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES (cached)
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      
      ../meson.build:57:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
      The following exception(s) were encountered:
      Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
      Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
      Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
      Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"
      
      A full log can be found at /private/var/folders/0v/nkjttv413cgb2b1z262v54rm0000gn/T/pip-install-pm0emj9q/scipy_95d22f3313394ae88360cc627ecfbef3/.mesonpy-9osi9ko5/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Desktop (please complete the following information):**
 - OS: Mac OS 14.6.1 (23G93)
 - Version 14.6.1 (23G93)

**Comment by MAYAS3** [comment]
Hello @gen-li,

Pip seems to have an issue building Scipy. Could you try to reinstall without using your cached version by running `pip install --no-cache-dir deepparse[app]` ?

If it doesn't solve the issue, please let me know the python version you're using and whether you're on Intel or Apple Silicon.

**Comment by gen-li** [comment]
Hi @MAYAS3 ,

Thanks for your help. The issue still exists.

I am using Apple Silicon. The python version is Python 3.12.4

Here is the error from the new try.

Collecting deepparse[app]
  Downloading deepparse-0.9.12-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: numpy<2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from deepparse[app]) (1.26.4)
Requirement already satisfied: torch in /opt/anaconda3/lib/python3.12/site-packages (from deepparse[app]) (2.4.1)
Collecting bpemb (from deepparse[app])
  Downloading bpemb-0.3.5-py3-none-any.whl.metadata (19 kB)
Collecting scipy<=1.10.1 (from deepparse[app])
  Downloading scipy-1.9.3.tar.gz (42.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.1/42.1 MB 115.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      + meson setup /private/var/folders/0v/nkjttv413cgb2b1z262v54rm0000gn/T/pip-install-veetdw1x/scipy_f167dd7b262048959334228c26bd6826 /private/var/folders/0v/nkjttv413cgb2b1z262v54rm0000gn/T/pip-install-veetdw1x/scipy_f167dd7b262048959334228c26bd6826/.mesonpy-x3_t_09d -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/private/var/folders/0v/nkjttv413cgb2b1z262v54rm0000gn/T/pip-install-veetdw1x/scipy_f167dd7b262048959334228c26bd6826/.mesonpy-x3_t_09d/meson-python-native-file.ini
      The Meson build system
      Version: 1.5.1
      Source dir: /private/var/folders/0v/nkjttv413cgb2b1z262v54rm0000gn/T/pip-install-veetdw1x/scipy_f167dd7b262048959334228c26bd6826
      Build dir: /private/var/folders/0v/nkjttv413cgb2b1z262v54rm0000gn/T/pip-install-veetdw1x/scipy_f167dd7b262048959334228c26bd6826/.mesonpy-x3_t_09d
      Build type: native build
      Project name: SciPy
      Project version: 1.9.3
      C compiler for the host machine: cc (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.3.9.4)")
      C linker for the host machine: cc ld64 1053.12
      C++ compiler for the host machine: c++ (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.3.9.4)")
      C++ linker for the host machine: c++ ld64 1053.12
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES (cached)
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      Fortran compiler for the host machine: gfortran (gcc 14.2.0 "GNU Fortran (Homebrew GCC 14.2.0) 14.2.0")
      Fortran linker for the host machine: gfortran ld64 530
      Compiler for Fortran supports arguments -Wno-conversion: YES
      Program cython found: YES (/private/var/folders/0v/nkjttv413cgb2b1z262v54rm0000gn/T/pip-build-env-6txee1de/overlay/bin/cython)
      Program pythran found: YES (/private/var/folders/0v/nkjttv413cgb2b1z262v54rm0000gn/T/pip-build-env-6txee1de/overlay/bin/pythran)
      Program cp found: YES (/bin/cp)
      Program python found: YES (/opt/anaconda3/bin/python)
      
      ../meson.build:85:2: ERROR: Problem encountered: Your Python version is too new. SciPy 1.9 supports Python 3.8-3.11; if you are trying to build from source for the most recent SciPy version you may hit this error as well. Please build from the `main` branch on GitHub instead.
      
      A full log can be found at /private/var/folders/0v/nkjttv413cgb2b1z262v54rm0000gn/T/pip-install-veetdw1x/scipy_f167dd7b262048959334228c26bd6826/.mesonpy-x3_t_09d/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by MAYAS3** [comment]
Hi @gen-li,

I've made a new release that allows for newer versions of Scipy that support python 3.12. Could you try again (`pip install --no-cache-dir deepparse[app]`)?

**Comment by gen-li** [comment]
It works now! Cool! Thanks so much!

Best,

Gen

**Comment by MAYAS3** [comment]
Great! Enjoy Deepparse!
