### ISSUE TITLE
Use memory mapping when loading embeddings

### ISSUE THREAD

**Issue by freud14** [GRAAL-Research/deepparse#41]
One idea for a future release would be to load the embeddings via memory mapping instead of loading them all into memory. 

For fasttext, it seems that the Fasttext API does not support memory mapping. However, [gensim seems to support it](https://radimrehurek.com/gensim/models/fasttext.html#gensim.models.fasttext.FastText.load) but not with the fasttext format. So, either we save the current embeddings in a format readable by memory mapping in the gensim API and we upload them somewhere (GRAIL website server???) or we take embeddings provided by gensim and we retrain a model with them. 

For BPEmb, I haven't checked but it's less bad with regard to memory usage.

**Comment by davebulaval** [comment]
#54
