### ISSUE TITLE
Model weights are not available

### ISSUE THREAD

**Issue by nathanshartmann** [GRAAL-Research/deepparse#52]
Trying to download weights from http://graal-research.github.io/deepparse-external-assets/bpemb.ckpt.

https://www.graal-research.github.io website seems to be offline.

**Comment by davebulaval** [comment]
Sorry, will fix it right away, I've moved the assets but forgot to push it in master and in a new release.

**Comment by davebulaval** [comment]
@nathanshartmann I'm waiting for the build and tests to push a new version. Will be up and running in a couple of minutes.

**Comment by davebulaval** [comment]
Fixed with release 0.11.2 #53

**Comment by davebulaval** [comment]
I've made a version mistake in the rush, notice I've pushed a newer version 0.1.2 instead of 0.11.2.
