### ISSUE TITLE
[FEATURE] Release train and test dataset

### ISSUE THREAD

**Issue by davebulaval** [GRAAL-Research/deepparse#74]
Release the dataset (in pickle format)

- Add a README file with the dataset
- Add a LICENSE
- Add the link in doc and GitHub README

**Comment by davebulaval** [comment]
ETA january

**Comment by harirajeev** [comment]
Hi , any update on releasing train and test datasets ? Thanks

**Comment by davebulaval** [comment]
There you go https://github.com/GRAAL-Research/deepparse-address-data
