### ISSUE TITLE
Retrain Issue with "bpemb" model

### ISSUE THREAD

**Issue by chandrai** [GRAAL-Research/deepparse#97]
While retraining with "bpemb" model_type, the model is not at all running. Its getting stuck forever. No checkpoints are getting created as well. What could be the reason?

<img width="1135" alt="Screen Shot 2021-08-20 at 5 24 59 PM" src="https://user-images.githubusercontent.com/39342768/130229460-f90f4e9d-7bed-40f3-a575-f69f10f9ec97.png">

**Comment by davebulaval** [comment]
@chandrai do you still have a problem?

**Comment by chandrai** [comment]
> @chandrai do you still have a problem?

I ran it in GPU and then it worked. In cpu, it was not running.
